services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  model-downloader:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    depends_on:
      - ollama
    restart: "no"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for Ollama to be ready..."
        until ollama list > /dev/null 2>&1; do
          sleep 2
        done
        echo "Downloading model: hf.co/mradermacher/Llama-PLLuM-8B-instruct-GGUF:Q4_K_S"
        ollama pull "hf.co/mradermacher/Llama-PLLuM-8B-instruct-GGUF:Q4_K_S"

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - model-downloader
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'DEFAULT_MODELS=["hf.co/mradermacher/Llama-PLLuM-8B-instruct-GGUF:Q4_K_S"]'
      - 'ENABLE_EVALUATION_ARENA_MODELS=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}